### ISSUE TITLE
How to score just one new user at a time

### ISSUE THREAD

**Issue by jmadison222** [ocelma/python-recsys#10]
I need to be able to score one new user without having to recalculate the model.  For example, we'll be loading a few million historical records of customers and what they bought.  We can do this offline and are not too worried about run-time.

But then, each time a new user comes into our system, we need to score them and make recommendations without rebuilding the model.  How do we do that?

Just as a mock-up, it would be something like this:

     svd.load_data(filename=sFileSource, sep=',', format=dictFormat)
     k = 5 # Number of clusters
     svd.compute(
         k=k, min_values=3, pre_normalize=None, 
         mean_center=False,
         post_normalize=True, savefile=sFileTarget
     )

Where we can do this overnight and are not worried if it takes a while.  But then, when a new, never-seen user comes in, we can put in the products they bought and get a recommendation.  Sort of like this code, which does *not* do what I'm describing, but emulates it:

    svd.add_tuple((1.0, 1, 88))
    svd.add_tuple((1.0, 2, 88))
    svd.add_tuple((1.0, 61, 88))
    svd.recommend(88, n=3, is_row=False, only_unknowns=True)

While we don't worry if the model build takes a while, we do need the recommendation of a new user to happen in about on second.

How can we go about doing that?

**Comment by fedeisas** [comment]
Hi @jmadison222! Did you manage to solve this? Or ended up using another library? Thanks!

**Comment by ocelma** [comment]
The library does not allow to do this.
But you can do something very similar:

```
svd.add_tuple((1.0, 1, 88))
svd.add_tuple((1.0, 2, 88))
svd.add_tuple((1.0, 61, 88))

orig_recs = svd.recommend(88, n=3, is_row=False, only_unknowns=True)

NUM_SIMILARS = 5 # or 10 or 20
new_items = [1,2,61]
for new_item_id in new_items:
    new_recs += svd.similar(new_item_id, NUM_SIMILARS)

# TODO: combine orig_recs and the more relevant recommendations coming from the new_recs
```
