### ISSUE TITLE
Factorise.py file showing indentation error in each line after line 15  even though there is not  any

### ISSUE THREAD

**Issue by abhinabyu** [ocelma/python-recsys#11]
After doing step 1 (load data set) it shows error in line 15 and onwards of factorise.py(i am new to python)
is there something i am doing wrong
1)i installed python first
2)then pip and dependies
3)then placed movie lens data set in respective places
4)install python-recys-master

Now when i run first step this error
even though i have installed divis2
::

Traceback (most recent call last):
  File "load.py", line 1, in <module>
    from recsys.algorithm.factorize import SVD
  File "/home/abhimanyu/Desktop/python-recsys-master/recsys/algorithm/factorize.py", line 15, in <module>
    from csc import divisi2
ImportError: No module named csc

**Comment by ocelma** [comment]
Hi, 

looks like csc-pysparse library was not installed.
Try this:
```
sudo pip install csc-pysparse
```
or this:
```
sudo easy_install csc-pysparse
```

and then check that the CSC library is installed: 
```
$ python -c "from csc import divisi2"
```

**Comment by abhinabyu** [comment]
Hi,
thanks for the reply but,I am still getting same error What i am doing is
this:
1)I installed Python-2.7.9 on desktop
2)Then i go python 2.7.9 directory and installed all three libraries by
copy pasting the commands

But when installing CSC-pysparse following warning comes.
 No blas info found
    Using BLAS info:
    {}
    build_src
    building py_modules sources
    building extension "pysparse.sparse.spmatrix" sources
    building data_files sources
    build_src: building npy-pkg config files

    warning: no files found matching '*.txt'
    warning: no previously-included files found matching
'pysparse/__config__.py'
    warning: no previously-included files found matching 'pysp


is this the issue of due to compatibility or something??

**Comment by ocelma** [comment]
I don't think the warnings are the issue.

What message (if any) do you get when you run this command-line?

```
 $ python -c "from csc import divisi2"
```

**Comment by abhinabyu** [comment]
Hi,
This is the message i got :

abhimanyu@abhi-pc:~$ python -c "from csc import divisi2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named csc

**Comment by abhinabyu** [comment]
After re installation of all library these are the screen shots of
CSC-pysparse

**Comment by abhinabyu** [comment]
it was python version issue now all   libraries are installed.
Thanks for help

**Comment by TungTNguyen** [comment]
How did you pass through it, I got the same issue as yours

**Comment by thuvh** [comment]
@TungTNguyen 

> Traceback (most recent call last):
File "load.py", line 1, in 
from recsys.algorithm.factorize import SVD
File "/home/abhimanyu/Desktop/python-recsys-master/recsys/algorithm/factorize.py", line 15, in 
from csc import divisi2
**ImportError: No module named csc**

you should understand this error message, is csc package installed?

**Comment by TungTNguyen** [comment]
Yes, it's not. I don't know about the module I did `pip install csc-pysparse`
in the console, it tells me that pip is installing the setup.py file. Then something goes kike Visual Studio C++ 9 is required 
Thanks for your help, in advance

**Comment by thuvh** [comment]
When you install csc-pyspare package, there are some required libraries and they need to be compiled, so that Visual Studio C++ 9 is required to compile them.
