### ISSUE TITLE
SVD.compute() kernel fail on Windows

### ISSUE THREAD

**Issue by mylesg** [ocelma/python-recsys#14]
Used the Movielens SVD example in my class tonight to show them a rec system. 

People (including me) who were using a MAC went though the tutorial without issues.

All people on Windows (7 and 8.1): the kernel fails on the "svd.compute" step. 

I believe everyone is using the 2.7+ Anaconda version of Python. 

thoughts?

**Comment by ocelma** [comment]
I'm afraid I can't help you here.
It's been a while since I tested it on Windows. No idea why it could be failing.

Did you get any error message? Or it just crashed?

**Comment by mylesg** [comment]
I am having them install these two packages first. 

pip install csc-pysparse networkx divisi2 
pip install https://github.com/ocelma/python-recsys/zipball/master <https://github.com/ocelma/python-recsys/zipball/master>

Then they run your example. It does this error at the svd.compute(). All people on Windows are having this issues. But works perfect on Mac.

Love your thoughts.

Myles










Begin forwarded message:

**Comment by rickjunli** [comment]
hi - i am running into the same kernel fail issue on windows too at the svd.compute() step. do we have any solutions to the issue? thanks.

**Comment by ocelma** [comment]
Unfortunately I don't have any solution for this Windows issue. I have no
way to test it in this environment.
