### ISSUE TITLE
SVD.similar() user or item

### ISSUE THREAD

**Issue by fedeisas** [ocelma/python-recsys#16]
When trying to get `SVD.similarity(i, j)`, how do I specify if I'm looking users or items?

Thanks!

http://ocelma.net/software/python-recsys/build/html/api.html#recsys.algorithm.baseclass.Algorithm.similarity

**Comment by ocelma** [comment]
Both svd.similar() and svd.similarity() look at the rows (not columns) in the matrix.
So, depending on how you create the matrix, you'll be able to compute (only) user or item similarity.

**Comment by fedeisas** [comment]
Thanks a lot @ocelma!
