### ISSUE TITLE
How to increase the number of similarity/recommending item results

### ISSUE THREAD

**Issue by rkt2015** [ocelma/python-recsys#22]
Hi, now I am testing recsys algorithm for only similar users finding. Each output result contains 10 users with similarity scores (actually it has 9 similar users and 1 search/target user). I want to increase the number of results from 10 to 50. I couldn't find about it in documentation of parameter setting . Could you please give me a direction?

**Comment by ocelma** [comment]
The .similar(i, n=10) method has a parameter 'n'. Default value is 10. You can pass another, greater, value to return more similar items

See documentation here: http://ocelma.net/software/python-recsys/build/html/api.html#algorithms

**Comment by rkt2015** [comment]
Thank you very much.
