### ISSUE TITLE
Getting error while laoding the data.

### ISSUE THREAD

**Issue by dilipbobby** [ocelma/python-recsys#23]
I want to try out the python-recsys but it is giving me the error while loading the movie ratings mail.

**>>>  svd.load_data(filename='./movierates.dat', sep='::', format={'col':0,'row':1,'value':2,'ids': int})

Error (ID is not int) while reading: [u'userId', u'movieId', u'rating', u'timestamp']
Error while reading: [u'']**

**Comment by ocelma** [comment]
Please check that your input data has integers for all userId values (you're setting 'ids': int, in the parameters)

The error is telling you that most likely they aren't

**Comment by ocelma** [comment]
Actually there's a value in the UserId field that's '**'
Hence the error
