### ISSUE TITLE
 RuntimeWarning: invalid value encountered in divide ----Special characters in user_id

### ISSUE THREAD

**Issue by FrancyPinedaB77** [ocelma/python-recsys#24]
hi, please I need to do recommender with id_user="X3escB3aJ_rP1u5DaTN9cw" but It does not allow it because the character hyphen.
in the case id_user="X3escB3aJ_rP1u5DaTN9cw" 

_**"X3escB3aJ_rP1u5DaTN9cw
Creating matrix (426351 tuples)
Matrix density is: 0.0237%
Updating matrix: squish to at least 10 values
Computing svd k=10, min_values=10, pre_normalize=None, mean_center=True, post_normalize=True
[WARNING] mean_center is True. svd.similar(...) might return nan's. If so, then do svd.compute(..., mean_center=False)
/root/anaconda2/lib/python2.7/site-packages/divisi2/dense.py:269: RuntimeWarning: invalid value encountered in divide
  return self / norms
Traceback (most recent call last):
  File "ejemplo.py", line 47, in <module>
    recomendaciones= svd.recommend(id_user, n=10,is_row=False)
  File "build/bdist.linux-x86_64/egg/recsys/algorithm/factorize.py", line 352, in recommend
  File "build/bdist.linux-x86_64/egg/recsys/algorithm/factorize.py", line 300, in _get_col_reconstructed
  File "/root/anaconda2/lib/python2.7/site-packages/divisi2/labels.py", line 65, in col_named
    return self[:,self.col_index(label)]
  File "/root/anaconda2/lib/python2.7/site-packages/divisi2/labels.py", line 57, in col_index
    return self.col_labels.index(label)
KeyError: 'X3escB3aJ_rP1u5DaTN9cw'"**_

Thanks

**Comment by ocelma** [comment]
How do you know is because the hypen?
The library allows *any* string as an ID.
The error I'm seeing is that there's no key for that User Id (not that the
string has an hypen, hence it fails).
You should make sure that the matrix is correctly created.

**Comment by FrancyPinedaB77** [comment]
Because when used L2p0vO3fsS2LC6hhQo3CzA the recommendation works

**Comment by ocelma** [comment]
Can you try changing the input data, removing all hyphens?
So you will have this id instead: X3escB3aJrP1u5DaTN9cw

Then check that all works fine?

Thanks

**Comment by FrancyPinedaB77** [comment]
Thanks, the error is by  the number min_values = 10
Solved
