### ISSUE TITLE
 x Neighbours in svd.recommend

### ISSUE THREAD

**Issue by FrancyPinedaB77** [ocelma/python-recsys#25]
hi, 

Please i need to know the parameter for x Neighbours, for the user :USERID, in the recommender
For example x=100 Neighbours

svd.recommend(USERID, is_row=False) 

http://ocelma.net/software/python-recsys/build/html/algorithm.html?highlight=recommend

thanks

**Comment by ocelma** [comment]
It's documented here: http://ocelma.net/software/python-recsys/build/html/api.html

recommend(..., n=10)
