### ISSUE TITLE
ImportError: No module named algorithm

### ISSUE THREAD

**Issue by BayanN** [ocelma/python-recsys#26]
when I run Movielens I get the error ImportError: No module named algorithm. I have installed all the packages execpt divisi2, it keeps failing to install. My python version is 2.7. Is there a way to make it work or to install divisi2 with another way other than pip?

**Comment by ocelma** [comment]
I honestly don't know.
In order to run this library you need divisi2 installed.
It works fine with 2.7. so you should be good.
Yet, until you install the dependency you won't be able to use this library,
