### ISSUE TITLE
IndexError: Error creating second index list

### ISSUE THREAD

**Issue by FrancyPinedaB77** [ocelma/python-recsys#27]
hi 

I have this 
user=1
stars=nn.get("rating")
movie_id=nn.get("movieId")
id_user=nn.get("userId")
tupla=(stars,movie_id,id_user) #if tupla=(4.0, 1193, 2)
data.add_tuple(tupla)

and I have this problem when:
recomendaciones= svd.recommend(user, n=10, only_unknowns=True, is_row=False)

ERROR

  File "/usr/local/lib/python2.7/dist-packages/pysparse/sparse/pysparseMatrix.py", line 149, in __getitem__
    m = self.matrix[index]
IndexError: Error creating second index list
![image](https://cloud.githubusercontent.com/assets/20497274/25835209/8234b03e-3442-11e7-853b-47c4591aa9fd.png)

**Comment by ocelma** [comment]
Hi,

I'm missing some context here. Given your code snippet, I can't tell why it fails.

Could you please try to run the Movielens dataset (example here: http://ocelma.net/software/python-recsys/build/html/examples.html#movielens ) and let me know if it works.

**Comment by FrancyPinedaB77** [comment]
Thank you

Already solved
