### ISSUE TITLE
Can we load data using pandas dataframe?

### ISSUE THREAD

**Issue by dilipbobby** [ocelma/python-recsys#28]
Hi,
 In the code example the Input data is taken from a file.
```
svd.load_data(filename='./data/movielens/ratings.dat',
            sep='::',
            format={'col':0, 'row':1, 'value':2, 'ids': int}) 
```
can we load pandas dataframe in the place of file-Input ? please share a code snippet if yes.

**Comment by ocelma** [comment]
Hi, 

Well, this library is old and back then I didn't know about Pandas (early days) existence. 
So, there's no support for Pandas as input data.
Yet, I encourage you to create a patch, and add this functionality in the library.
You, and many other people, will benefit from this.
