### ISSUE TITLE
Divisi2 what/where  is it ?

### ISSUE THREAD

**Issue by Sandy4321** [ocelma/python-recsys#34]
link from 
http://ocelma.net/software/python-recsys/build/html/installation.html
for Divisi2
gives
https://github.com/commonsense/conceptnet5/wiki/API

**Comment by ocelma** [comment]
I've updated the README.md with th Divis2 link: https://github.com/commonsense/divisi2
But both my library and Divisi2 are outdated.
i recommend you have a look at surpriselib python library, instead: http://surpriselib.com/
